import '../styles/globals.css'
import Header from './Header'
import { Providers } from './providers'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <title>Meta Messenger</title>
      </head>
      <body>
      <Header />
        {children}
      </body>
    </html>
  )
}
